import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("login", "routes/login.tsx"),
    route("register", "routes/register.tsx"),
    route("map-view", "routes/map-view.tsx"),
    route("jalan-desa", "routes/jalan-desa.tsx"),
    route("jalan-desa/:slug", "routes/jalan-desa.$slug.tsx"),
    route("statistik", "routes/statistik.tsx"),
    route("proxy/geonode-datasets", "routes/api/geonode-datasets.ts"),
    route("proxy/geoserver/*", "routes/api/geoserver.ts"),
    route("proxy/basemap", "routes/api/basemap-proxy.ts"),
    route("proxy/tileserv/*", "routes/api/tileserv.ts"),
    route("katalog-dataset", "routes/katalog-dataset.tsx"),
    route("katalog-dataset/:slug", "routes/katalog-dataset.$slug.tsx"),
    route("form-id/:idForm", "routes/realisasi-publik.tsx", { id: "form-id-publik" }),
    route("form-realisasi-infrastruktur/:idForm", "routes/realisasi-publik.tsx", { id: "form-realisasi-publik-legacy" }),
    // Admin routes
    route("admin", "routes/sidebar-layout.tsx", [
        index("routes/dashboard/index.tsx"),
        route("dashboard", "routes/dashboard/index.tsx", { id: "admin-dashboard" }),
        route("profile", "routes/profile/index.tsx"),
        route("planning/ploting-anggaran", "routes/planning/ploting-anggaran/index.tsx"),
        route("monitoring/laporan-realisasi", "routes/monitoring/laporan-realisasi/index.tsx"),
        route("monitoring/dokumen-infrastruktur", "routes/monitoring/dokumen-infrastruktur/index.tsx"),
        route("data-spasial/bataswilayah-desa", "routes/data-spasial/bataswilayah-desa/index.tsx"),
        route("data-spasial/bataswilayah-kecamatan", "routes/data-spasial/bataswilayah-kecamatan/index.tsx"),
        route("master/basemaps", "routes/master/basemaps/index.tsx"),
        route("master/layers", "routes/master/layers/index.tsx"),
        route("master/sessions", "routes/master/sessions/index.tsx"),
        route("master/users", "routes/master/users/index.tsx"),
        route("master/roles", "routes/master/roles/index.tsx"),
        route("master/permissions", "routes/master/permissions/index.tsx"),
        route("master/menus", "routes/master/menus/index.tsx"),
        route("master/menu-access", "routes/master/menu-access/index.tsx"),
        route("data-spasial/infrastruktur-jalan-desa", "routes/data-spasial/infrastruktur-jalan-desa/index.tsx"),
        route("master/opd", "routes/master/opd/index.tsx"),
        route("monitoring", "routes/monitoring/realisasi-infrastruktur/index.tsx", { id: "monitoring-main" }),
        route("monitoring/maps", "routes/monitoring/maps/index.tsx"),
        route("monitoring/peta-infrastruktur", "routes/monitoring/peta-infrastruktur/index.tsx"),
        route("monitoring/realisasi-infrastruktur", "routes/monitoring/realisasi-infrastruktur/index.tsx"),
        route("monitoring/agregasi-anggaran", "routes/monitoring/agregasi-anggaran/index.tsx"),
        route("monitoring/rekap-jalan", "routes/monitoring/rekap-jalan/index.tsx"),
        route("monitoring/form-realisasi", "routes/monitoring/form-realisasi/index.tsx"),
        route("monitoring/realisasi-entry", "routes/monitoring/realisasi-entry/index.tsx"),
        route("monitoring/laporan-formulir-desa", "routes/monitoring/laporan-formulir-desa/index.tsx"),
        route("data-monitoring", "routes/data-monitoring/index.tsx"),
        route("usulan-desa", "routes/usulan-desa/index.tsx"),
        route("usulan-desa/registrasi", "routes/usulan-desa/registrasi/index.tsx"),
        route("usulan-desa/edit/:id", "routes/usulan-desa/registrasi/index.tsx", { id: "usulan-desa-edit" }),
        route("usulan-desa/kategori", "routes/usulan-desa/kategori/index.tsx"),
        route("usulan-desa/daftar-usulan", "routes/usulan-desa/daftar-usulan/index.tsx"),
        route("usulan-desa/detail/:id", "routes/usulan-desa/detail/$id.tsx"),
        route("manage/infrastruktur", "routes/manage/infrastruktur/index.tsx"),
        route("manage/infrastruktur/tambah", "routes/manage/infrastruktur/form.tsx"),
        route("manage/infrastruktur/edit/:id", "routes/manage/infrastruktur/form.tsx", { id: "manage-infrastruktur-edit" }),
    ]),
] satisfies RouteConfig;
